version: '3.8'

services:
  postgres:
    image: postgres:11.16
    expose:
      - "5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    env_file: .env

  redis:
    image: redis:alpine
    expose:
      - "6379"

  web:
    build: .
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
#    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8080 core.wsgi"
    volumes:
      - .:/usr/src/app
      - ./media:/usr/src/app/media
      - ./static:/usr/src/app/static
    env_file: .env
    depends_on:
      - postgres

  worker:
    build: .
    command: celery -A booking_api worker -l info
    volumes:
      - .:/usr/src/app
      - ./media:/usr/src/app/media
      - ./static:/usr/src/app/static
    env_file: .env
    depends_on:
      - postgres