# Generated by Django 4.1.3 on 2022-12-10 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
