# Generated by Django 4.1.3 on 2022-12-05 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_element_element_slug_element_is_booked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checking_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 5, 17, 2, 18, 304807, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkout_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 5, 17, 2, 18, 307838, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
