# Generated by Django 4.1.3 on 2022-12-05 17:06

from django.db import migrations, models
import main.models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_reservation_checking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checking_date',
            field=models.DateTimeField(blank=True, default=main.models.Reservation, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkout_date',
            field=models.DateTimeField(blank=True, default=main.models.Reservation, null=True),
        ),
    ]
