# Generated by Django 4.1.3 on 2022-12-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_booking_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
