# Generated by Django 4.1.3 on 2022-12-05 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_element_element_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_slug',
            field=models.SlugField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checking_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkout_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
