# Generated by Django 4.1.3 on 2022-12-08 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_element_element_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.DeleteModel(
            name='HotelsIk',
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.RemoveField(
            model_name='element',
            name='category',
        ),
        migrations.RemoveField(
            model_name='element',
            name='price',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='confirm_reservation',
        ),
        migrations.AddField(
            model_name='checkin',
            name='element',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.element'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
